In [1]:
import numpy as np
import yaml
import re

In [12]:
with open('/media/auv/pushyami_disk/calibrations/mulit_cam/final_extrinsic/multi_5_cam_calib-camchain.yaml', 'r') as file:
    data = yaml.safe_load(file)
T_1_0 = np.array(data['cam1']['T_cn_cnm1'])
T_2_1 = np.array(data['cam2']['T_cn_cnm1'])
T_3_2 = np.array(data['cam3']['T_cn_cnm1'])
print(T_1_0)
print(T_2_1)
print(T_3_2)

T_3_1 = T_3_2 @ T_2_1
T_1_3 = np.linalg.inv(T_3_1)
print(T_1_3)

[[ 9.99911477e-01  2.24356588e-03  1.31150678e-02 -1.63674515e-01]
 [-2.29570606e-03  9.99989517e-01  3.96189190e-03  6.22143812e-04]
 [-1.31060416e-02 -3.99164952e-03  9.99906145e-01 -6.03653878e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 9.99836398e-01 -3.47371496e-04 -1.80847042e-02 -1.65035987e-01]
 [ 2.70894510e-04  9.99991012e-01 -4.23109951e-03 -4.02265671e-04]
 [ 1.80860114e-02  4.22550824e-03  9.99827506e-01 -3.33126925e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 9.99787185e-01 -2.49935329e-03  2.04777315e-02 -1.63308641e-01]
 [ 2.49948547e-03  9.99996876e-01  1.91393999e-05 -3.43812966e-04]
 [-2.04777154e-02  3.20484658e-05  9.99790309e-01  1.01578801e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 9.99993301e-01  2.77031637e-03 -2.39213760e-03  3.28378087e-01]
 [-2.76009957e-03  9.99987101e-01  4.26378375e-03  2.51636876e-04]
 [ 2.40391877e-03 -4.25715265e-03  9.99988049e-01  6.339050

In [3]:
T_1_0 = np.array([[0.9998970414154913, 0.0025184436935303924, 0.014126712636293616, -0.16510559543517186],
          [-0.0025747376916538563, 0.9999888121459206, 0.00396816189293617, 0.0006589960385436992],
          [-0.014116560996399857, -0.004004125916088403, 0.9998923390452003, 0.001185414073395764],
          [0.0, 0.0, 0.0, 1.0]])
T_2_1 = np.array([[0.9998168950215246, 0.004994742836137566, -0.018472384077656275, -0.16666801213807167],
                  [-0.0050763000128554265, 0.9999775632371579, -0.0043708352118666085, 0.0001550475955388289],
                  [0.018450138419293247, 0.00446380625371011, 0.9998198171800917, -0.00218357555447604],
                  [0.0, 0.0, 0.0, 1.0]])
T_3_2 = np.array([[0.999804994836766, -0.0003661072331576076, 0.01974432234704442, -0.16478446379174938],
                  [0.00035004901889049107, 0.9999996051860355, 0.0008167578914832194,-0.0002438614902792721],
                  [-0.019744613572682087, -0.0008096871388110293, 0.9998047282552721, 0.0011821211726795004],
                  [0.0,  0.0,  0.0, 1.0]])
T_4_3 = np.array([[0.9999899506890185, -0.0027798772538932368, -0.003517215294813596, -0.16565728110703087],
                  [0.002765892825584954, 0.9999882760045843, -0.003974630833051912, -0.00038626161841776084],
                  [0.003528223044843023, 0.003964862650200667, 0.9999859156539722, 0.00017314031001560586],
                  [0.0,  0.0,  0.0, 1.0]])
T_2_i = np.array([[-0.011612754703408945, 0.9999086461026788, -0.0069168907254490986, 0.2492073620312688],
                  [-0.004508174438135337, 0.006864932260559925, 0.9999662739654247, 0.004961868689304041],
                  [0.9999224071353914, 0.011643545601202065, 0.004428041824433238, -0.052176174006792614],
                  [0.0, 0.0, 0.0, 1.0]])

T_5_i = np.array([[0.9987883341189624, -0.009143750557613899, 0.048355511098619505, 0.0406018557354875],
                  [-0.04820621796951958, 0.01589793642828108, 0.9987108771643564, 0.16265008759326582],
                  [-0.009900715981369539, -0.9998318095775224, 0.015437887808692818, -0.36341097130911876],
                  [0.0, 0.0, 0.0, 1.0]])
T_6_i = np.array([[-0.9984763884180592, 0.014896632093210849, -0.053131837196784715, 0.02567640938442857],
                  [-0.05310712395214018, 0.0020499628717092645, 0.9985867168342235, 0.15749398193904],
                  [0.014984497227405882, 0.9998869376106987, -0.0012557222374918863, 0.13311318215776366],
                  [0.0, 0.0, 0.0, 1.0]])



#Our cam chain, 1, 2,3,5,6

T_5_3 = T_5_i @ np.linalg.inv(T_2_i) @ np.linalg.inv(T_3_2)

T_6_5 = T_6_i @ np.linalg.inv(T_5_i)

print(T_5_3)

print(T_6_5)

T_3_1 = T_3_2 @ T_2_1

print(np.linalg.inv(T_3_1))

[[-0.001367    0.04459679  0.99900413  0.09635609]
 [ 0.00831996  0.998971   -0.04458393  0.15470634]
 [-0.99996445  0.00825073 -0.00173663 -0.28020802]
 [ 0.          0.          0.          1.        ]]
[[-9.99971997e-01 -4.69374760e-03 -5.82873883e-03  6.49223390e-02]
 [-4.77434914e-03  9.99892100e-01  1.38922502e-02  1.03887906e-04]
 [ 5.76290319e-03  1.39196896e-02 -9.99886509e-01 -2.32754569e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 0.99998807 -0.00471124 -0.00129035  0.33146144]
 [ 0.0047158   0.99998256  0.00355465  0.00170391]
 [ 0.00127358 -0.00356069  0.99999285 -0.00186801]
 [ 0.          0.          0.          1.        ]]
